plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  "semantic-release-plugin-decorators@*":
    dependencies:
      "@semantic-release/commit-analyzer": "*"
      "@semantic-release/release-notes-generator": "*"
      "@semantic-release/git": "*"
      "@semantic-release/github": "*"
      "@semantic-release/npm": "*"

  "chalk@*":
    dependencies:
      "#ansi-styles": npm:ansi-styles@latest
      "#supports-color": npm:supports-color@latest
