nodeLinker: node-modules

npmPublishAccess: public

npmScopes:
  picodegallo:
    npmAuthToken: "${NPM_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  chalk@*:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@latest"
      "#supports-color": "npm:supports-color@latest"
  semantic-release-plugin-decorators@*:
    dependencies:
      "@semantic-release/commit-analyzer": "*"
      "@semantic-release/git": "*"
      "@semantic-release/github": "*"
      "@semantic-release/npm": "*"
      "@semantic-release/release-notes-generator": "*"
      "@suin/semantic-release-yarn": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
