plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  "semantic-release-plugin-decorators@*":
    dependencies:
      "@semantic-release/commit-analyzer": "latest"
      "@semantic-release/release-notes-generator": "latest"
      "@semantic-release/git": "latest"
      "@semantic-release/github": "latest"
      "@semantic-release/npm": "latest"
  "@semantic-release/npm@*":
    dependencies:
      "chalk": "latest"
      "npmlog": "latest"
      "proc-log": "latest"
      "semver": "latest"
      "validate-npm-package-name": "latest"
