name: main
on: push

jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.5.0

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Yarn Caching
        uses: actions/setup-node@v3
        with:
          node-version: 18.5.0
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install

      - name: Build all packages
        run: yarn build

      - name: Save cli artifact
        uses: actions/upload-artifact@master
        with:
          if-no-files-found: ignore
          name: picodegallo-cli-build-${{ github.sha }}
          path: packages/cli/.dist

  publish-cli:
    runs-on: ubuntu-latest
    needs: [ build-cli ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.5.0

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Yarn Caching
        uses: actions/setup-node@v3
        with:
          node-version: 18.5.0
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install

      - name: Get built artifact
        uses: actions/download-artifact@master
        with:
          name: picodegallo-cli-build-${{ github.sha }}
          path: packages/cli/.dist

      - name: Semantic Release
        run: |
          NPM_TOKEN=${{ secrets.NPM_TOKEN }} GH_TOKEN=${{ secrets.GH_TOKEN }} yarn workspace @picodegallo/cli run release

      - name: Release to npm
        run: |
          NPM_TOKEN=${{ secrets.NPM_TOKEN }} yarn publish --tolerate-republish --access public
