name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['cli', 'recipes-commander']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.7.0

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Yarn Caching
        uses: actions/setup-node@v3
        with:
          node-version: 18.7.0
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install

      - name: Build all packages
        run: yarn workspace @picodegallo/${{ matrix.package }} build

      - name: Save cli artifact
        uses: actions/upload-artifact@master
        with:
          if-no-files-found: ignore
          name: picodegallo-${{ matrix.package }}-build-${{ github.sha }}
          path: packages/${{ matrix.package }}/.dist

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.7.0

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Yarn Caching
        uses: actions/setup-node@v3
        with:
          node-version: 18.7.0
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install

      - name: Get built artifact
        uses: actions/download-artifact@master
        with:
          name: picodegallo-${{ matrix.package }}-build-${{ github.sha }}
          path: packages/${{ matrix.package }}/.dist

      - name: Semantic Release
        run: |
          NPM_TOKEN=${{ secrets.NPM_TOKEN }} GH_TOKEN=${{ secrets.GH_TOKEN }} yarn workspace @picodegallo/${{ matrix.package }} run release
