name: main
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: [ 'jest' ]
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.FORESIGHT_TOKEN }}
      - uses: actions/checkout@v3
      - name: Test Package
        uses: dmeents/maestro/src/github-actions/test-standard@main
        with:
          testSuite: ${{ matrix.suite }}
          codeCovSecret: ${{ secrets.CODECOV_TOKEN }}
          foresightKey: ${{ secrets.FORESIGHT_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    strategy:
      fail-fast: false
      matrix:
        package:
          - cli
          - recipes-commander
          - recipes-react
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.FORESIGHT_TOKEN }}
      - name: Checkout Picodegallo
        uses: actions/checkout@v3
      - name: Build @picodegallo/cli
        uses: dmeents/maestro/src/github-actions/test-standard@main
        with:
          namespace: '@picodegallo'
          packageName: ${{ matrix.package }}

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package:
          - cli
          - recipes-commander
          - recipes-react
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.FORESIGHT_TOKEN }}
      - name: Checkout Picodegallo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get latest code
        run: git pull origin main
      - name: Release @picodegallo/cli
        uses: dmeents/maestro/src/github-actions/test-standard@main
        with:
          namespace: '@picodegallo'
          packageName: ${{ matrix.package }}
          npmToken: ${{ secrets.NPM_TOKEN }}
          githubToken: ${{ secrets.GH_TOKEN }}
