name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - cli
          - recipes-commander
    steps:
      - name: Checkout Picodegallo
        uses: actions/checkout@v3
      - name: Checkout Maestro Actions
        uses: actions/checkout@v3
        with:
          repository: dmeents/maestro
          path: ./maestro
      - name: Build @picodegallo/cli
        uses: ./maestro/src/github-actions/build-standard
        with:
          namespace: '@picodegallo'
          packageName: ${{ matrix.package }}

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package:
          - cli
          - recipes-commander
    steps:
      - name: Checkout Picodegallo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get Repository Head
        run: git pull
      - name: Checkout Maestro Actions
        uses: actions/checkout@v3
        with:
          repository: dmeents/maestro
          path: ./maestro
      - name: Release @picodegallo/cli
        uses: ./maestro/src/github-actions/release-standard
        with:
          namespace: '@picodegallo'
          packageName: ${{ matrix.package }}
          npmToken: ${{ secrets.NPM_TOKEN }}
          githubToken: ${{ secrets.GH_TOKEN }}
