name: main
on: push

jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build @picodegallo/cli
        uses: dmeents/maestro/src/github-actions/build-standard
        with:
          packageName: '@picodegallo/cli'
          isMonorepo: 'true'

  publish:
    runs-on: ubuntu-latest
    needs: [ build-cli ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Release @picodegallo/cli
        uses: dmeents/maestro/src/github-actions/release-standard
        with:
          packageName: '@picodegallo/cli'
          isMonorepo: 'true'
          npmToken: ${{ secrets.NPM_TOKEN }}
          githubToken: ${{ secrets.GH_TOKEN }}
